language: python
python:
  - "3.6"

notifications:
    on_success: never
    on_failure: always


install:
  - pip install pandas
  - pip install sklearn
  - pip install scipy
  - 'pip install codecov'
  - 'pip install pytest-cov'

script:
  - pytest
  - pytest --cov=./

after_success:
  - codecov
